# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: prompthub-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: prompthub
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - prompthub-network

  redis:
    image: redis:7-alpine
    container_name: prompthub-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - prompthub-network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prompthub-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:${MONGO_PASSWORD}@mongodb:27017/prompthub?authSource=admin
      - MONGODB_DB_NAME=prompthub
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./app:/app
    networks:
      - prompthub-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: prompthub-ui
    restart: always
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - fastapi
    volumes:
      - ./streamlit_app:/app
    networks:
      - prompthub-network

volumes:
  mongodb_data:
  redis_data:

networks:
  prompthub-network:
    driver: bridge